- name: Upgrade packages with winget
  hosts: windows
  tasks:
    - name: Run a command under PowerShell
      ansible.windows.win_shell: |
        winget upgrade --all
      register: winget_output

    - name: Show output
      debug:
        var: winget_output.stdout
